name: Testomatio Tests

on:
  workflow_dispatch:
    inputs:
      grep:
        description: 'tests to grep '
        required: false
        default: ''
      run:
        required: false
      testomatio:
        required: false
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        npm install
        npm install codeceptjs
        codeceptjs init
        npm install puppeteer
        npx codeceptjs run --steps
    env:
      TESTOMATIO: "${{ github.event.inputs.testomatio }}"
      TESTOMATIO_RUN: "${{ github.event.inputs.run }}"
